pipeline {
    agent any

    
    stages {
        stage('build') {
            steps {
                git 'https://github.com/gopinathPersonal/sampleJavaProject.git'
                sh 'mvn clean install'
                sh 'javac HelloWorldTest.java'
            }
        }
        stage('Run') {
            steps {
                sh 'java HelloWorldTest'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}
